import React from "react";
import Head from "next/head";

export const BasicHead = ({ title }: { title?: string }) => {
 return (
  <Head>
   <title>{title ? title : "Circon's - Your circle of experts!"}</title>
   <meta name="description" content="Generated by create next app" />
   <meta name="viewport" content="width=device-width, initial-scale=1" />
   <link rel="icon" href="http://localhost:3000/image/favicon.ico" />
   <link rel="apple-touch-icon" sizes="180x180" href="image/apple-touch-icon.png" />
   <link rel="icon" type="image/png" sizes="32x32" href="image/favicon-32x32.png" />
   <link rel="icon" type="image/png" sizes="16x16" href="image/favicon-16x16.png" />
   <link rel="manifest" href="image/site.webmanifest"></link>

   <meta property="og:title" content="Cisron's - Your circle of experts!" />
   <meta property="og:site_name" content="Cisron's" />
   <meta property="og:url" content="exemple.com" />
   <meta property="og:description" content="Business advisory, Accounting & Audit, Financial advisory, Legalisation, Cryptocurrency" />
   <meta property="og:type" content="book" />
   <meta property="og:image" content="image/circonOG.png"></meta>
  </Head>
 )
}