backend:
  # name: git-gateway
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
  - label: "Business advisory"
    name: "Areas_business_advisory"
    folder: "content/services/business"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Accounting & Audit"
    name: "Areas_accounting_audit"
    folder: "content/services/accounting-audit"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Financial advisory"
    name: "Areas_Financial_advisory"
    folder: "content/services/financial"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Legalisation"
    name: "Areas_Legalisation"
    folder: "content/services/legal"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Digital"
    name: "Areas_digital"
    folder: "content/services/digital"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "News"
    name: "News"
    folder: "content/news"
    create: true
    identifier_field: name
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub text", name: "subText", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}