backend:
  # name: git-gateway
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - label: 'Partners'
          name: "partners"
          widget: list
          fields:
            - { label: "Logo", name: "logo", widget: "image"}
            - { label: "Description", name: "description", widget: "text"}
        - label: 'Testimonials'
          name: "testimonials"
          widget: list
          fields:
            - label: 'Author'
              name: "author"
              widget: "object"
              fields:
                - { label: "Name", name: "name", widget: "string"}
                - { label: "Avatar", name: "avatar", widget: "image"}
            - { label: "Text", name: "text", widget: "text"}
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - label: 'Team'
          name: "team"
          widget: list
          fields:
            - label: "Member"
              name: "member"
              widget: "object"
              fields:
                - { label: "Name", name: "name", widget: "string"}
                - { label: "Avatar", name: "avatar", widget: "image"}
                - { label: "Position", name: "position", widget: "text"}
                - label: "Link"
                  name: "socialLink"
                  widget: list
                  fields:
                    - label: "Type Link"
                      name: "type"
                      widget: "select"
                      options: ["telegram", "linkedIn"]
                    - { label: "Link", name: "link", widget: "text" }
  - label: "Business advisory"
    name: "Areas_business_advisory"
    folder: "content/services/business"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Accounting & Audit"
    name: "Areas_accounting_audit"
    folder: "content/services/accounting-audit"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Financial advisory"
    name: "Areas_Financial_advisory"
    folder: "content/services/financial"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Legalisation"
    name: "Areas_Legalisation"
    folder: "content/services/legal"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Digital"
    name: "Areas_digital"
    folder: "content/services/digital"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "News"
    name: "News"
    folder: "content/news"
    create: true
    identifier_field: name
    fields:
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub text", name: "subText", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - label: 'Author'
        name: "Author"
        widget: "object"
        fields:
          - { label: "Name", name: "name", widget: "string"}
          - { label: "Avatar", name: "avatar", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      