import React from 'react'
import Head from 'next/head'
import HomePage from '../src/components/Home/HomePage'
import { NavBar } from '../src/components/NavBar/NavBar'
import { useRouter } from 'next/router'
import { attributes, react as HomeContent } from '../content/home.md'

export default function Home() {
  const { locale, locales, defaultLocale } = useRouter();
  const { cats, title, lang } = attributes
  return (
    <>
      <Head>
        <title>Citcons</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <NavBar />
        <HomePage />
      </main>
    </>
  )
}
