import React from "react";
import Head from 'next/head'
import NewsPage from '../src/components/News/NewsPage'
import { NavBar } from "../src/components/NavBar/NavBar";

export default function News() {
 return (
  <>
   <>
    <Head>
     <title>Citcons - areas</title>
     <meta name="description" content="Generated by create next app" />
     <meta name="viewport" content="width=device-width, initial-scale=1" />
     <link rel="icon" href="/favicon.ico" />
    </Head>
    <main >
     <NavBar />
     <NewsPage />
    </main>
   </>
  </>
 )
}